---
languages:
  0: JavaScript
  1: Java
  2: Python
  3: Ruby
  4: PHP
  5: C++
  6: C#
  7: C
  8: Go
  9: Other

db:
  host: localhost
  port: 27017
  name: counter-stats

listen:
  port: 3000
  backlog: 1024
